apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  ports:
  - port: 5672
    targetPort: 5672
    nodePort: 30002  # Choose a port in the range 30000-32767
    name: amqp
  - port: 15672
    targetPort: 15672
    nodePort: 30003  # Choose a port in the range 30000-32767
    name: management
  selector:
    app: rabbitmq
