apiVersion: v1
kind: Service
metadata:
  name: publisher-service
spec:
  selector:
    app: publisher
  type: NodePort
  ports:
  - protocol: TCP
    port: 6767
    targetPort: 6767
    nodePort: 30001
  
