apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
      - name: publisher
        image: tharinduyasantha/publisher-node:latest
        ports:
        - containerPort: 7878
        env:
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ_URL
