apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
    nodePort: 30003
  - name: management
    port: 15672
    targetPort: 15672
    nodePort: 30004
  selector:
    app: rabbitmq
