apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
      - name: subscriber
        image: tharinduyasantha/subscriber-node:latest
        ports:
        - containerPort: 7879
        env:
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ_URL
