apiVersion: v1
kind: Service
metadata:
  name: subscriber-service
spec:
  selector:
    app: subscriber
    type: NodePort
  ports:
    - protocol: TCP
      port: 7879
      targetPort: 7879
      nodePort: 30002